Fix a system server crash
 * If we get into a state where the backup data is null, system server
   will go down in flames. Abort and kill any active agents if this
   happens.

java.lang.NullPointerException: Attempt to invoke virtual method 'java.io.FileDescriptor android.os.ParcelFileDescriptor.getFileDescriptor()' on a null object reference
        at com.android.server.backup.BackupManagerService$PerformBackupTask.operationComplete(BackupManagerService.java:2820)
        at com.android.server.backup.BackupManagerService$BackupHandler.handleMessage(BackupManagerService.java:778)
        at android.os.Handler.dispatchMessage(Handler.java:102)
        at android.os.Looper.loop(Looper.java:135)
        at android.os.HandlerThread.run(HandlerThread.java:61)

Change-Id: I65cb3c7d75a417373e8a59b9150a61b5eb1939af

Conflicts:
	services/backup/java/com/android/server/backup/BackupManagerService.java